name: Build and publish

on:
  push:
    branches:
      - '13-add-docker-support'
  pull_request: # on a pull request to each of these branches
    branches:
      - 'master'

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.5.0 # Checking out the repo

      - name: Build and publish "latest" Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.PACKAGES_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: DCSSB-next-stats
          dockerfile: Dockerfile
